#!/usr/bin/env python3
"""Generate human-readable docs from the sources of truth.

The intent is to keep the prose, the schemas, the prompts, the policies, and
the model allowlist from drifting. Every generated file contains a "DO NOT
EDIT" banner and the SHA-256 of the inputs that produced it; CI re-runs this
script with ``--check`` and fails if the working tree is not byte-identical
to what would be regenerated.

Generated outputs (under ``docs/generated/``):

* ``schemas.md``    — every JSON Schema rendered as a property table.
* ``prompts.md``    — index of LLM prompts with stage/version metadata.
* ``policies.md``   — index of OPA policies with their package + summary.
* ``models.md``     — frontier model allowlist as a table.
* ``mcp.md``        — MCP server allowlist as a table.
* ``cli.md``        — ``agentic-alz --help`` output for every subcommand.

Usage:

    python scripts/gen_docs.py            # write
    python scripts/gen_docs.py --check    # exit non-zero if anything would change
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import io
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED = REPO_ROOT / "docs" / "generated"

BANNER = (
    "<!-- AUTOGENERATED by scripts/gen_docs.py from {sources}. "
    "DO NOT EDIT BY HAND. Regenerate with `python scripts/gen_docs.py`. "
    "Inputs SHA-256: {sha} -->\n\n"
)


def _sha(*paths: Path) -> str:
    h = hashlib.sha256()
    for p in sorted(paths):
        h.update(p.read_bytes())
    return h.hexdigest()


# ---------------------------------------------------------------------------
# schemas.md
# ---------------------------------------------------------------------------
def render_schemas() -> tuple[str, list[Path]]:
    schemas_dir = REPO_ROOT / "schemas"
    files = sorted(schemas_dir.glob("*.schema.json"))
    out = io.StringIO()
    out.write("# JSON Schemas\n\n")
    out.write(
        "Every typed contract crossing a stage boundary in Agentic ALZ is a "
        "JSON Schema in [`schemas/`](../../schemas/). This page is generated "
        "from those files.\n\n"
    )
    for f in files:
        schema = json.loads(f.read_text(encoding="utf-8"))
        out.write(f"## `{f.name}`\n\n")
        out.write(f"- **`$id`**: `{schema.get('$id', '—')}`\n")
        out.write(f"- **Title**: {schema.get('title', '—')}\n")
        if "description" in schema:
            out.write(f"\n{schema['description']}\n\n")
        else:
            out.write("\n")
        _render_properties(out, schema)
        out.write("\n")
    return out.getvalue(), files


def _render_properties(out: io.StringIO, schema: dict[str, Any]) -> None:
    props = schema.get("properties") or {}
    if not props:
        return
    required = set(schema.get("required") or [])
    out.write("| Property | Type | Required | Description |\n")
    out.write("| --- | --- | :---: | --- |\n")
    for name, sub in props.items():
        ty = _type_of(sub)
        req = "✓" if name in required else " "
        desc = (sub.get("description") or "").replace("\n", " ").strip()
        if "enum" in sub:
            desc = (desc + " " if desc else "") + f"Enum: `{sub['enum']}`."
        if "const" in sub:
            desc = (desc + " " if desc else "") + f"Constant: `{sub['const']}`."
        if "pattern" in sub:
            desc = (desc + " " if desc else "") + f"Pattern: `{sub['pattern']}`."
        out.write(f"| `{name}` | {ty} | {req} | {desc} |\n")
    out.write("\n")


def _type_of(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return f"`{node['$ref'].rsplit('/', 1)[-1]}`"
    t = node.get("type")
    if isinstance(t, list):
        return " \\| ".join(f"`{x}`" for x in t)
    if t == "array":
        items = node.get("items") or {}
        return f"array of {_type_of(items)}"
    if t == "object":
        return "`object`"
    return f"`{t or 'any'}`"


# ---------------------------------------------------------------------------
# prompts.md
# ---------------------------------------------------------------------------
PROMPT_RX = re.compile(
    r"^# (?P<title>.+?)\n+> Stage: `(?P<stage>[^`]+)`\.?(?P<rest>.*?)$",
    re.DOTALL,
)


def render_prompts() -> tuple[str, list[Path]]:
    prompts_dir = REPO_ROOT / "prompts"
    files = sorted(prompts_dir.glob("*.md"))
    out = io.StringIO()
    out.write("# LLM prompts\n\n")
    out.write(
        "Versioned prompt files for the four LLM stages defined in the "
        "consensus plan. Each prompt declares its stage, its allowed tools, "
        "and its output contract. Source: [`prompts/`](../../prompts/).\n\n"
    )
    out.write("| File | Stage | First-line title |\n")
    out.write("| --- | --- | --- |\n")
    for f in files:
        text = f.read_text(encoding="utf-8")
        title = text.splitlines()[0].lstrip("# ").strip() if text else "—"
        m = re.search(r"Stage: `([^`]+)`", text)
        stage = m.group(1) if m else "—"
        out.write(f"| [`{f.name}`](../../prompts/{f.name}) | `{stage}` | {title} |\n")
    return out.getvalue(), files


# ---------------------------------------------------------------------------
# policies.md
# ---------------------------------------------------------------------------
def render_policies() -> tuple[str, list[Path]]:
    pol_dir = REPO_ROOT / "policies"
    files = sorted(pol_dir.glob("*.rego"))
    out = io.StringIO()
    out.write("# OPA / Conftest policies\n\n")
    out.write(
        "Deterministic guardrails enforced on every PR. Source: "
        "[`policies/`](../../policies/).\n\n"
    )
    out.write("| File | Package | One-line summary |\n")
    out.write("| --- | --- | --- |\n")
    for f in files:
        text = f.read_text(encoding="utf-8")
        pkg_m = re.search(r"^\s*package\s+([A-Za-z0-9_.]+)", text, re.MULTILINE)
        pkg = pkg_m.group(1) if pkg_m else "—"
        # First non-empty comment line.
        summary = "—"
        for line in text.splitlines():
            s = line.strip()
            if s.startswith("#") and len(s) > 2 and "policy" in s.lower():
                summary = s.lstrip("# ").rstrip(".")
                break
        out.write(f"| [`{f.name}`](../../policies/{f.name}) | `{pkg}` | {summary} |\n")
    return out.getvalue(), files


# ---------------------------------------------------------------------------
# models.md
# ---------------------------------------------------------------------------
def render_models() -> tuple[str, list[Path]]:
    src = REPO_ROOT / "docs" / "models.allowlist.yaml"
    raw = yaml.safe_load(src.read_text(encoding="utf-8"))
    out = io.StringIO()
    out.write("# Frontier-model allowlist\n\n")
    out.write(
        "Single source of truth: "
        "[`docs/models.allowlist.yaml`](../models.allowlist.yaml). "
        f"Last reviewed: **{raw.get('last_reviewed', '—')}**.\n\n"
    )
    out.write("| Model id | Provider | Family | Approved roles | Notes |\n")
    out.write("| --- | --- | --- | --- | --- |\n")
    for m in raw.get("models", []):
        roles = ", ".join(f"`{r}`" for r in m.get("role", []))
        out.write(
            f"| `{m['id']}` | {m['provider']} | {m['family']} | {roles} | "
            f"{m.get('notes', '')} |\n"
        )
    return out.getvalue(), [src]


# ---------------------------------------------------------------------------
# mcp.md
# ---------------------------------------------------------------------------
def render_mcp() -> tuple[str, list[Path]]:
    src = REPO_ROOT / "docs" / "mcp.allowlist.yaml"
    raw = yaml.safe_load(src.read_text(encoding="utf-8"))
    out = io.StringIO()
    out.write("# MCP server allowlist\n\n")
    out.write(
        "Single source of truth: "
        "[`docs/mcp.allowlist.yaml`](../mcp.allowlist.yaml). "
        f"Last reviewed: **{raw.get('last_reviewed', '—')}**.\n\n"
    )
    out.write(
        "Every code path that reaches an MCP tool must call "
        "`agentic_alz.mcp.assert_allowed(server, tool, mode)`. "
        "Adding a server in `mode: write` requires a NetSec CODEOWNER on the PR; "
        "the OPA policy [`policies/mcp_allowlist.rego`](../../policies/mcp_allowlist.rego) "
        "refuses any `write` entry without a `netsec_approval` block.\n\n"
    )
    out.write("| Server id | Transport | Mode | Tools | Notes |\n")
    out.write("| --- | --- | --- | --- | --- |\n")
    for s in raw.get("servers", []):
        tools = ", ".join(f"`{t}`" for t in s.get("tools", []))
        notes = (s.get("notes") or "").replace("\n", " ").strip()
        out.write(
            f"| `{s['id']}` | `{s['transport']}` | `{s['mode']}` | {tools} | {notes} |\n"
        )
    out.write("\n")
    # NetSec approvals appendix.
    write_entries = [s for s in raw.get("servers", []) if s.get("mode") == "write"]
    if write_entries:
        out.write("## NetSec approvals (mode: write)\n\n")
        out.write("| Server id | Reviewer | Date | Justification |\n")
        out.write("| --- | --- | --- | --- |\n")
        for s in write_entries:
            ap = s.get("netsec_approval") or {}
            just = (ap.get("justification") or "").replace("\n", " ").strip()
            out.write(
                f"| `{s['id']}` | {ap.get('reviewer', '—')} | "
                f"{ap.get('date', '—')} | {just} |\n"
            )
        out.write("\n")
    return out.getvalue(), [src]


# ---------------------------------------------------------------------------
# cli.md
# ---------------------------------------------------------------------------
def render_cli() -> tuple[str, list[Path]]:
    out = io.StringIO()
    out.write("# `agentic-alz` CLI reference\n\n")
    out.write(
        "Generated by invoking `agentic-alz <cmd> --help`. The CLI exposes "
        "the deterministic stages of the pipeline; LLM stages are exercised "
        "through the orchestrator runtime.\n\n"
    )
    sources = [REPO_ROOT / "orchestrator" / "agentic_alz" / "cli.py"]
    commands = [
        [],
        ["validate-inputs"],
        ["generate"],
        ["risk"],
        ["tf-policy"],
        ["judge"],
        ["models"],
    ]
    # Pin COLUMNS so click's help text wraps deterministically regardless of
    # the host terminal — required for `--check` to be reliable in CI.
    # PYTHONUTF8=1 forces the subprocess to use UTF-8 stdout/stderr on Windows
    # (where the default is the system ANSI codepage, e.g. cp1252 / cp437).
    env = {**__import__("os").environ, "COLUMNS": "100", "TERM": "dumb", "PYTHONUTF8": "1"}
    for cmd in commands:
        argv = ["agentic-alz", *cmd, "--help"]
        try:
            res = subprocess.run(
                argv, capture_output=True, text=True, encoding="utf-8", check=False, env=env
            )
            help_text = res.stdout or res.stderr
        except FileNotFoundError:
            help_text = "(agentic-alz CLI not installed)"
        label = "(root)" if not cmd else f"`agentic-alz {' '.join(cmd)}`"
        out.write(f"## {label}\n\n```\n{help_text.rstrip()}\n```\n\n")
    return out.getvalue(), sources


# ---------------------------------------------------------------------------
# roadmap.md
# ---------------------------------------------------------------------------
def render_roadmap() -> tuple[str, list[Path]]:
    """Render ROADMAP.md as a deterministic status table.

    Live open/closed/in-progress state lives on GitHub Issues (the squad
    bootstrap is responsible for that). This generated page is the
    structural view: id, title, milestone, labels, agent eligibility,
    dependencies — all derivable from the roadmap file alone, so the
    generated-docs gate stays deterministic.
    """
    roadmap = REPO_ROOT / "ROADMAP.md"
    script = REPO_ROOT / "scripts" / "squad_bootstrap.py"
    # Import the parser from squad_bootstrap.py so there's a single source of
    # truth for how the roadmap is read.
    spec = importlib.util.spec_from_file_location("squad_bootstrap_for_docs", script)
    assert spec and spec.loader
    sb = importlib.util.module_from_spec(spec)
    # Register before exec_module so dataclass introspection can resolve
    # __module__ via sys.modules — required by Python 3.12+.
    sys.modules["squad_bootstrap_for_docs"] = sb
    spec.loader.exec_module(sb)
    items = sb.parse_roadmap(roadmap.read_text(encoding="utf-8"))

    out = io.StringIO()
    out.write("# Roadmap\n\n")
    out.write(
        "Generated from [`ROADMAP.md`](../../ROADMAP.md). The roadmap is the "
        "single source of truth for planned work; "
        "[`scripts/squad_bootstrap.py`](../../scripts/squad_bootstrap.py) "
        "upserts one GitHub issue per item (idempotent via the "
        "`<!-- roadmap-id: ... -->` marker) and assigns the Copilot cloud "
        "agent when an item is opted in. See "
        "[`../squad.md`](../squad.md).\n\n"
    )
    # Group by milestone, preserving roadmap order.
    by_milestone: dict[str, list] = {}
    for it in items:
        by_milestone.setdefault(it.milestone, []).append(it)
    for milestone, group in by_milestone.items():
        out.write(f"## {milestone}\n\n")
        out.write("| id | Title | Agent eligible | Labels | Depends on |\n")
        out.write("| --- | --- | :---: | --- | --- |\n")
        for it in group:
            agent = "✓" if it.agent_eligible else " "
            labels = ", ".join(f"`{lbl}`" for lbl in it.labels)
            deps = ", ".join(f"`{d}`" for d in it.depends_on) or "—"
            out.write(f"| `{it.id}` | {it.title} | {agent} | {labels} | {deps} |\n")
        out.write("\n")
    return out.getvalue(), [roadmap, script]


# ---------------------------------------------------------------------------
# README index
# ---------------------------------------------------------------------------
def render_index() -> tuple[str, list[Path]]:
    out = io.StringIO()
    out.write("# Generated documentation\n\n")
    out.write(
        "These files are produced by [`scripts/gen_docs.py`](../../scripts/gen_docs.py) "
        "from the sources of truth in `schemas/`, `prompts/`, `policies/`, "
        "the model allowlist, and the orchestrator CLI. Do not edit by hand — "
        "edit the source and regenerate.\n\n"
        "- [`schemas.md`](schemas.md)\n"
        "- [`prompts.md`](prompts.md)\n"
        "- [`policies.md`](policies.md)\n"
        "- [`models.md`](models.md)\n"
        "- [`mcp.md`](mcp.md)\n"
        "- [`cli.md`](cli.md)\n"
        "- [`roadmap.md`](roadmap.md)\n"
        "- [`playbooks-index.md`](playbooks-index.md)\n"
        "- [`agent-instructions-hash.md`](agent-instructions-hash.md)\n"
        "- [`decisions-index.md`](decisions-index.md)\n"
    )
    return out.getvalue(), []


# ---------------------------------------------------------------------------
# playbooks-index.md
# ---------------------------------------------------------------------------
_PLAYBOOK_RX = re.compile(r"^([0-9]{2})-[a-z0-9-]+\.md$")


def render_playbooks_index() -> tuple[str, list[Path]]:
    """Render the routing table: playbook → triggers → CI checks → CODEOWNERS.

    The table is built from the playbooks themselves so it stays in lock-step
    with the source. CI checks are extracted from the ``## Definition of
    Done`` section by matching backticked tokens of the form
    ``<workflow-stem> / <job>`` where ``<workflow-stem>`` is the basename of
    a real file in ``.github/workflows/``.
    """
    pb_dir = REPO_ROOT / "docs" / "playbooks"
    files = sorted(p for p in pb_dir.glob("*.md") if _PLAYBOOK_RX.match(p.name))
    co_path = REPO_ROOT / "CODEOWNERS"
    co_text = co_path.read_text(encoding="utf-8") if co_path.is_file() else ""
    workflows_dir = REPO_ROOT / ".github" / "workflows"
    workflow_stems = sorted(p.stem for p in workflows_dir.glob("*.yml"))
    ci_ref_rx = re.compile(
        r"`(" + "|".join(re.escape(w) for w in workflow_stems) + r")\s*/\s*([^`]+)`"
    ) if workflow_stems else None

    out = io.StringIO()
    out.write("# Playbooks — routing index\n\n")
    out.write(
        "Generated from `docs/playbooks/` and `CODEOWNERS`. The hand-written "
        "summary lives at [`../playbooks/README.md`](../playbooks/README.md); "
        "this page is the machine-readable view used by `lint-instructions` "
        "and by the squad bootstrapper to map labels to playbooks.\n\n"
    )
    out.write("| # | Playbook | Triggers (excerpt) | CI checks | Sensitive |\n")
    out.write("| --- | --- | --- | --- | :---: |\n")
    for f in files:
        text = f.read_text(encoding="utf-8")
        # Triggers excerpt: first non-blank line under "## Triggers".
        trig_excerpt = "—"
        m = re.search(r"^##\s+Triggers\s*\n(.+?)(?=^##\s)", text, re.DOTALL | re.MULTILINE)
        if m:
            for line in m.group(1).splitlines():
                s = line.strip().lstrip("- ").strip()
                if s and not s.startswith(">"):
                    trig_excerpt = s.replace("|", "\\|")
                    break
        # CI checks: only count `<workflow-stem> / <job>` tokens.
        ci_block = re.search(
            r"^##\s+Definition of Done\s*\n(.+?)(?=^##\s|\Z)",
            text,
            re.DOTALL | re.MULTILINE,
        )
        ci_checks: list[str] = []
        if ci_block and ci_ref_rx is not None:
            for wf, job in ci_ref_rx.findall(ci_block.group(1)):
                ci_checks.append(f"`{wf} / {job.strip()}`")
        ci_str = ", ".join(sorted(set(ci_checks))) or "—"
        sensitive = "✓" if f"docs/playbooks/{f.name}" in co_text else " "
        title_m = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
        title = title_m.group(1) if title_m else f.stem
        nn_match = _PLAYBOOK_RX.match(f.name)
        assert nn_match is not None  # filtered above
        nn = nn_match.group(1)
        out.write(
            f"| {nn} | [`{f.name}`](../playbooks/{f.name}) — {title} | "
            f"{trig_excerpt[:80]} | {ci_str} | {sensitive} |\n"
        )
    out.write("\n")
    out.write(
        "## Sensitive playbooks\n\n"
        "A ✓ above means the playbook governs a path that appears in "
        "`CODEOWNERS` with a non-default reviewer. Edits to those playbooks "
        "themselves require the same reviewer.\n"
    )
    return out.getvalue(), [*files, co_path]


# ---------------------------------------------------------------------------
# agent-instructions-hash.md
# ---------------------------------------------------------------------------
def render_agent_instructions_hash() -> tuple[str, list[Path]]:
    """Record the SHA-256 of the canonical agent-instruction surfaces.

    ``AGENTS.md`` is canonical; ``.github/copilot-instructions.md`` is the
    deliberate stub pointing at it. Both files carry the marker
    ``<!-- agent-instructions-canonical-source: AGENTS.md -->`` and a
    matching ``<!-- agent-instructions-version: vN -->`` line — the
    ``lint-instructions`` job verifies the markers are present and equal.
    The hash recorded below makes any drift visible in PR diffs.
    """
    sources: list[Path] = [
        REPO_ROOT / "AGENTS.md",
        REPO_ROOT / ".github" / "copilot-instructions.md",
        REPO_ROOT / "prompts" / "system" / "agent-preamble.v1.md",
    ]
    out = io.StringIO()
    out.write("# Agent-instruction surfaces — content hash\n\n")
    out.write(
        "`AGENTS.md` is the single source of truth for agent instructions in "
        "this repo. The Copilot stub at `.github/copilot-instructions.md` and "
        "the runtime preamble at `prompts/system/agent-preamble.v1.md` are "
        "the editor-time and runtime mirrors. The hashes below make any "
        "drift visible in PR diffs; the `lint-instructions` job in `ci.yml` "
        "verifies both stub-side files carry the canonical-source marker "
        "pointing at `AGENTS.md`.\n\n"
    )
    out.write("| File | Bytes | SHA-256 |\n")
    out.write("| --- | ---: | --- |\n")
    for p in sources:
        if not p.is_file():
            out.write(f"| `{p.relative_to(REPO_ROOT)}` | — | _missing_ |\n")
            continue
        data = p.read_bytes()
        out.write(
            f"| `{p.relative_to(REPO_ROOT)}` | {len(data)} | "
            f"`{hashlib.sha256(data).hexdigest()}` |\n"
        )
    return out.getvalue(), sources


# ---------------------------------------------------------------------------
# decisions-index.md
# ---------------------------------------------------------------------------
def render_decisions_index() -> tuple[str, list[Path]]:
    """Index the research decisions under decision/<id>/.

    Each subdirectory may contain a ``decision.json`` validated by
    ``schemas/decision.schema.json``. Folders without one are listed as
    "in progress"; folders with one show the chosen option, consensus
    level, and ADR link.
    """
    decision_dir = REPO_ROOT / "decision"
    schema = REPO_ROOT / "schemas" / "decision.schema.json"
    sources: list[Path] = [schema]
    out = io.StringIO()
    out.write("# Research decisions\n\n")
    out.write(
        "Index of `decision/<id>/` records produced by the "
        "[`10-research-and-decide.md`](../playbooks/10-research-and-decide.md) "
        "playbook. Each row links to the ADR synthesised from the decision "
        "(when one has been written).\n\n"
    )
    if not decision_dir.is_dir():
        out.write("_No decision records yet. Folder `decision/` will be created on first use._\n")
        return out.getvalue(), sources
    rows: list[str] = []
    for sub in sorted(p for p in decision_dir.iterdir() if p.is_dir()):
        dj = sub / "decision.json"
        if dj.is_file():
            try:
                data = json.loads(dj.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                rows.append(f"| `{sub.name}` | _invalid decision.json_ | — | — |")
                continue
            sources.append(dj)
            outcome = data.get("outcome") or {}
            adr = (data.get("adr") or {}).get("path") or "—"
            adr_cell = f"[`{adr}`](../../{adr})" if adr != "—" else "—"
            rows.append(
                f"| `{data.get('id', sub.name)}` | {data.get('title', '—')} | "
                f"`{outcome.get('chosen_option', '—')}` "
                f"({outcome.get('consensus', '—')}) | {adr_cell} |"
            )
        else:
            rows.append(f"| `{sub.name}` | _in progress_ | — | — |")
    if rows:
        out.write("| id | Title | Outcome | ADR |\n")
        out.write("| --- | --- | --- | --- |\n")
        for r in rows:
            out.write(r + "\n")
    else:
        out.write("_No decision records yet._\n")
    return out.getvalue(), sources


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
RENDERERS = {
    "schemas.md": render_schemas,
    "prompts.md": render_prompts,
    "policies.md": render_policies,
    "models.md": render_models,
    "mcp.md": render_mcp,
    "cli.md": render_cli,
    "roadmap.md": render_roadmap,
    "playbooks-index.md": render_playbooks_index,
    "agent-instructions-hash.md": render_agent_instructions_hash,
    "decisions-index.md": render_decisions_index,
    "README.md": render_index,
}


def build() -> dict[str, str]:
    """Return a {filename: content} map of everything that should be on disk."""
    out: dict[str, str] = {}
    for name, fn in RENDERERS.items():
        body, sources = fn()
        sha = _sha(*sources) if sources else "n/a"
        src_list = ", ".join(str(p.relative_to(REPO_ROOT)) for p in sources) or "(none)"
        out[name] = BANNER.format(sources=src_list, sha=sha) + body
    return out


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any generated file is not byte-identical.",
    )
    args = parser.parse_args(argv[1:])

    GENERATED.mkdir(parents=True, exist_ok=True)
    desired = build()
    diffs: list[str] = []
    for name, content in desired.items():
        target = GENERATED / name
        existing = target.read_text(encoding="utf-8") if target.is_file() else ""
        if existing != content:
            diffs.append(name)
            if not args.check:
                target.write_text(content, encoding="utf-8")
    if args.check and diffs:
        print(
            "ERROR: generated docs are stale. Re-run: python scripts/gen_docs.py",
            file=sys.stderr,
        )
        for d in diffs:
            print(f"  - docs/generated/{d}", file=sys.stderr)
        return 1
    if diffs and not args.check:
        for d in diffs:
            print(f"wrote docs/generated/{d}")
    elif not diffs:
        print("docs/generated/ is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
